#!/usr/bin/env python3
# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0
"""Regenerate the AMP-only template from a local checkout's pinned release."""
import argparse
from pathlib import Path
import subprocess
import tempfile

import yaml

RELEASE = "amp/v1.0.0"
SOURCE = "deployments/helm-charts/wso2-amp-thunder-extension"
MODULE = Path(__file__).resolve().parents[1]
FILES = [
    "50-amp-api-client.yaml", "53-amp-console-app.yaml",
    "56-amp-publisher-client.yaml", "57-amp-system-client.yaml",
    "58-amctl-client.yaml", "59-am-mcp-client.yaml",
    "60-amp-resource-server.yaml", "60-mcp-resource-servers.yaml",
    "61-amp-role-admin.yaml", "62-amp-role-developer.yaml",
    "63-amp-role-ai-lead.yaml", "64-amp-role-platform-engineer.yaml",
    "65-amp-group-admins.yaml", "66-amp-user-type-engineer.yaml",
    "72-am-observer-client.yaml",
    "73-am-obs-mcp-client.yaml",
]
SECRETS = {
    "amp-api-client": "AMP_API_CLIENT_SECRET",
    "amp-system-client": "AMP_SYSTEM_CLIENT_SECRET",
    "amp-publisher-client": "AMP_PUBLISHER_CLIENT_SECRET",
    "am-observer-client": "AM_OBSERVER_CLIENT_SECRET",
}


def generate(repo):
    def source(path):
        return subprocess.check_output(
            ["git", "-C", str(repo), "show", f"{RELEASE}:{SOURCE}/{path}"], text=True
        )

    with tempfile.TemporaryDirectory() as directory:
        chart = Path(directory)
        (chart / "templates").mkdir()
        (chart / "Chart.yaml").write_text("apiVersion: v2\nname: identity-source\nversion: 1.0.0\n")
        (chart / "values.yaml").write_text(source("values.yaml"))
        (chart / "templates/bootstrap.yaml").write_text(source("templates/amp-thunder-bootstrap.yaml"))
        rendered = subprocess.check_output(["helm", "template", "identities", str(chart)], text=True)
    configmap = next(d for d in yaml.safe_load_all(rendered) if d and d.get("kind") == "ConfigMap")
    documents = [d for name in FILES for d in yaml.safe_load_all(configmap["data"][name]) if d]
    for doc in documents:
        # All resource types use the actual OU UUID; applications do not resolve
        # ouHandle like the other import adapters do.
        doc.pop("ouHandle", None)
        doc["ouId"] = "${OU_ID}"
        if doc["resource_type"] == "user_type":
            # The console creates users with the "engineer" type by name. Keep
            # AMP's schema, but let USER_TYPES control which types can sign in.
            assert doc["name"] == "engineer", doc["name"]
        if doc["resource_type"] == "application":
            config = doc["inboundAuthConfig"][0]["config"]
            if doc["type"] == "browser":
                doc.pop("authFlowHandle", None)
                doc["authFlowId"] = "${AUTH_FLOW_ID}"
                doc["allowedUserTypes"] = "${USER_TYPES}"
                doc.pop("themeId", None)
                doc.pop("layoutId", None)
                doc.pop("logoUrl", None)
                config.pop("clientSecret", None)
                if config["clientId"] == "amp-console-client":
                    config["redirectUris"] = ["${CONSOLE_URL}/login"]
            else:
                config["clientSecret"] = "${" + SECRETS[config["clientId"]] + "}"
        if doc["id"] == "amp-admins":
            doc["members"] = "${ADMIN_MEMBERS}"
        if doc["id"] == "amp-agent-manager-mcp-resource-server":
            doc["identifier"] = "${API_URL}/mcp"
        if doc["id"] == "amp-observer-mcp-resource-server":
            doc["identifier"] = "${OBSERVER_URL}/mcp"
    # Equivalent system permission without rewriting Thunder's built-in role.
    documents.append({
        "resource_type": "role", "id": "amp-thunder-system-access",
        "name": "AMP Thunder System Access", "ouId": "${OU_ID}",
        "description": "Allows AMP's system client to administer Thunder identities",
        "permissions": [{"resourceServerId": "${THUNDER_SYSTEM_RESOURCE_ID}", "permissions": ["system"]}],
        "assignments": [{"id": "amp-system-client", "type": "app"}],
    })
    header = (
        "# Generated by scripts/generate-thunder-identities.py; do not edit manually.\n"
        "# Derived from WSO2 Agent Manager amp/v1.0.0 (Apache-2.0).\n"
        "# Source: https://github.com/wso2/agent-manager/blob/amp/v1.0.0/"
        + SOURCE + "/templates/amp-thunder-bootstrap.yaml\n"
        "# This is Thunder import YAML, NOT Kubernetes YAML. Render before import.\n"
        "# Includes the engineer user type the console creates users with.\n"
        "# Excludes shared configuration, users, and OpenChoreo clients.\n"
    )
    return header + yaml.safe_dump_all(documents, sort_keys=False, width=110)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("agent_manager_checkout", type=Path)
    args = parser.parse_args()
    (MODULE / "resources/amp-thunder-identities.yaml").write_text(generate(args.agent_manager_checkout))
